site_name: 向家祖训
theme: gitbook
repo_url: https://github.com/Xiang-Family/zuxun
repo_name: GitHub
plugins:
    - with-pdf:
        author: 向氏
        copyright: ' '
#        cover: false
        #back_cover: true
        #cover_title: TITLE TEXT
        cover_subtitle: ' '
        #custom_template_path: TEMPLATES PATH
        #
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        output_path: ../zuxun.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        show_anchors: false
        #verbose: true
